/*
 * conf_clock.h
 *
 * Created: 9/17/2017 10:36:25 PM
 *  Author: Jesse Banks
 */ 

#ifndef CONF_CLOCK_H_INCLUDED
#define CONF_CLOCK_H_INCLUDED

#define V2X_CLOCK_DEF

#define CONFIG_SYSCLK_SOURCE				SYSCLK_SRC_PLL
#define CONFIG_SYSCLK_PSADIV				SYSCLK_PSADIV_1
#define CONFIG_SYSCLK_PSBCDIV				SYSCLK_PSBCDIV_1_1
#define CONFIG_PLL0_SOURCE					PLL_SRC_RC2MHZ
#define CONFIG_PLL0_MUL						(16)
#define CONFIG_PLL0_DIV						(1)

#define CONFIG_USBCLK_SOURCE				USBCLK_SRC_RCOSC
#define CONFIG_OSC_RC32_CAL					48000000UL
#define CONFIG_OSC_AUTOCAL_RC32MHZ_REF_OSC  OSC_ID_USBSOF

#define CONFIG_RTC_SOURCE					SYSCLK_RTCSRC_TOSC

#endif /* CONF_CLOCK_H_INCLUDED */
